name = "carlson-elliptic-integrals"
author = "Jacob Williams"
copyright  = "Copyright (c) 2016-2022, Jacob Williams"
license = "BSD-3"
description = "Carlson symmetric forms of elliptic integrals"
homepage = "https://github.com/jacobwilliams/carlson-elliptic-integrals"
keywords = ["slatec", "elliptic integrals"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[library]
source-dir = "src"

[install]
library = true
