error_handler – carlson-elliptic-integrals
error_handler Subroutine
10 statements
Source File
private pure subroutine error_handler(routine, ier, error_code)
Error handler for the Carlson elliptic integral routines.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: routine
calling routine
integer, intent(out), optional :: ier
error flag (if not present, the program will stop)
integer, intent(in) :: error_code
error code (if ier is present, it will be set to this)
Called by
Source Code
    pure subroutine error_handler(routine, ier, error_code)
    character(len=*),intent(in) :: routine !! calling routine
    integer,intent(out),optional :: ier  !! error flag (if not present, the program will stop)
    integer,intent(in) :: error_code !! error code (if `ier` is present, it will be set to this)
    if (.not. present(ier)) then
        error stop 'Error in '//trim(routine)
    else
        ier = error_code
    end if
    end subroutine error_handler
Call graph
drc calls error_handler
drd calls error_handler
drf calls error_handler
drj calls error_handler, drc